apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
  namespace: default
  labels:
    app: my-app
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}"
data:
  config.json: |
    {
      "environment" : "dev"
    }