apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  selector:
    app: my-app  # Must match the label in the pods
  ports:
  - protocol: TCP
    port: 80       # Service port
    targetPort: 80 # Container port in the pods
  type: ClusterIP  # Options: ClusterIP, NodePort, or LoadBalancer (or Route in OpenShift)
